//! Build script for `nub-settings`.
//!
//! Reads `settings.toml` beside it and generates `settings_meta_data.rs`
//! in `$OUT_DIR` — `pub const SETTINGS: &[SettingMeta]`, `include!`d by
//! [`crate::meta`]. That table is the whole output: what a setting is
//! called in each source, what type it takes, and what it defaults to.
//!
//! Output is built as a plain `String` via `writeln!` — no proc-macro
//! dependencies, since the generated file is straightforward.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct SettingDef {
    #[serde(rename = "type")]
    type_: String,
    default: String,
    #[serde(default)]
    sources: Sources,
    /// Marks a setting as part of the npm-shared `.npmrc` surface: npm
    /// (and yarn / pnpm) also read this key from `.npmrc`, so
    /// `nub config set` writes it there to keep the multi-tool
    /// contract. Defaults to `false` — a setting only one tool reads is
    /// written to whichever file that tool owns.
    #[serde(default, rename = "npmShared")]
    npm_shared: bool,
    /// Marks a setting that shapes how `node_modules` is physically arranged
    /// rather than what resolves. See `SettingMeta::layout` for its reader.
    #[serde(default)]
    layout: bool,
}

#[derive(Debug, Default, Deserialize)]
struct Sources {
    #[serde(default)]
    cli: Vec<String>,
    #[serde(default)]
    env: Vec<String>,
    #[serde(default)]
    npmrc: Vec<String>,
    #[serde(default, rename = "workspaceYaml")]
    workspace_yaml: Vec<String>,
}

/// Cargo's `CARGO_MANIFEST_DIR`, read at RUN time rather than baked in by
/// `env!`. A build-script binary is cached per target dir, so an `env!` path
/// survives into any other checkout sharing that dir — reading the first
/// checkout's `settings.toml`, or failing outright once it is gone. Reading the
/// variable resolves per invocation instead.
fn manifest_dir() -> PathBuf {
    PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR")
            .expect("cargo always sets CARGO_MANIFEST_DIR for build scripts"),
    )
}

fn main() {
    // `settings.toml` lives inside this crate so it ships in the
    // published tarball — `cargo publish --verify` runs the build
    // script from `target/package/nub-settings-<ver>/`, which can
    // only see files under the crate root. That property comes from
    // where the file lives, not from how the path is resolved.
    let settings_path = manifest_dir().join("settings.toml");

    println!("cargo:rerun-if-changed={}", settings_path.display());
    // The path above is absolute, so a shared target dir would otherwise keep a
    // sibling worktree's generated settings without rerunning this script.
    println!("cargo:rerun-if-env-changed=CARGO_MANIFEST_DIR");

    let raw = fs::read_to_string(&settings_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", settings_path.display()));

    // Parse as an ordered map keyed by setting name. `BTreeMap` sorts
    // alphabetically which happens to match the order we want for the
    // generated slice anyway.
    let settings: BTreeMap<String, SettingDef> = toml::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", settings_path.display()));

    let mut out = String::from(
        "// GENERATED by build.rs from settings.toml. Do not edit by hand.\n\
         //\n\
         // Regenerated automatically when settings.toml changes (via\n\
         // cargo:rerun-if-changed).\n\n",
    );
    writeln!(out, "pub const SETTINGS: &[SettingMeta] = &[").unwrap();

    for (name, def) in &settings {
        writeln!(out, "    SettingMeta {{").unwrap();
        writeln!(out, "        name: {},", lit(name)).unwrap();
        writeln!(out, "        type_: {},", lit(&def.type_)).unwrap();
        writeln!(out, "        default: {},", lit(&def.default)).unwrap();
        writeln!(out, "        cli_flags: {},", slice_lit(&def.sources.cli)).unwrap();
        let env_vars = merged_env_vars(&def.sources.env);
        writeln!(out, "        env_vars: {},", slice_lit(&env_vars)).unwrap();
        let npmrc_keys = merged_npmrc_keys(&def.sources.npmrc);
        writeln!(out, "        npmrc_keys: {},", slice_lit(&npmrc_keys)).unwrap();
        writeln!(
            out,
            "        workspace_yaml_keys: {},",
            slice_lit(&def.sources.workspace_yaml)
        )
        .unwrap();
        writeln!(out, "        npm_shared: {},", def.npm_shared).unwrap();
        writeln!(out, "        layout: {},", def.layout).unwrap();
        writeln!(out, "    }},").unwrap();
    }

    writeln!(out, "];").unwrap();

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("settings_meta_data.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });
}

/// Auto-synthesize kebab↔camelCase aliases for every `.npmrc` key.
/// pnpm's `.npmrc` docs use kebab-case (`node-linker=hoisted`); its
/// `pnpm-workspace.yaml` uses camelCase (`nodeLinker: hoisted`). Users
/// paste both forms into `.npmrc` interchangeably, so each declared
/// key gets its opposite-case sibling added here. Without this, an
/// author who lists only `nodeLinker` would silently ignore users
/// copying `node-linker=...` out of pnpm docs (and vice versa).
///
/// Skips keys that aren't plain identifiers — registry-style entries
/// like `@scope:registry` or `//host/:_authToken` are pnpm syntax
/// rather than config-key identifiers, so kebab/camel conversion
/// doesn't apply.
fn merged_npmrc_keys(declared: &[String]) -> Vec<String> {
    let mut out: Vec<String> = Vec::with_capacity(declared.len() * 2);
    for src in declared {
        if !out.contains(src) {
            out.push(src.clone());
        }
    }
    for src in declared {
        if !is_case_convertible_key(src) {
            continue;
        }
        for alias in [to_kebab_case(src), to_camel_case(src)] {
            if alias != *src && !out.contains(&alias) {
                out.push(alias);
            }
        }
    }
    out
}

fn is_case_convertible_key(key: &str) -> bool {
    // Registry / auth keys like `@scope:registry`, `//host/:_authToken`,
    // and bracketed patterns aren't identifier-style config keys.
    // Leave them untouched.
    !(key.starts_with('/') || key.starts_with('@') || key.contains(':'))
}

/// Auto-synthesize the pnpm-compat env family from each declared
/// `npm_config_*` / `NPM_CONFIG_*` alias. pnpm v11 reads its general
/// settings from `pnpm_config_<name>` (lowercase) and `PNPM_CONFIG_<NAME>`
/// (uppercase, the v11 migration-guide spelling that replaces
/// `NPM_CONFIG_*`), so a setting that already declares the npm spelling
/// gets the matching pnpm spellings for free — no per-setting edit in
/// `settings.toml`, mirroring how [`merged_npmrc_keys`] synthesizes
/// kebab/camel aliases. Each pnpm alias lands immediately after the npm
/// alias it derives from.
///
/// Listing a spelling does not make nub read it: which prefixes a variable
/// may carry is decided by the reader, not by this table.
fn merged_env_vars(declared: &[String]) -> Vec<String> {
    let mut out: Vec<String> = Vec::with_capacity(declared.len() * 2);
    for alias in declared {
        out.push(alias.clone());
        let pnpm_alias = if let Some(rest) = alias.strip_prefix("npm_config_") {
            Some(format!("pnpm_config_{rest}"))
        } else {
            alias
                .strip_prefix("NPM_CONFIG_")
                .map(|rest| format!("PNPM_CONFIG_{rest}"))
        };
        if let Some(pnpm_alias) = pnpm_alias
            && !out.contains(&pnpm_alias)
        {
            out.push(pnpm_alias);
        }
    }
    out
}

fn to_kebab_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let mut prev_lower = false;
    for c in s.chars() {
        if c == '.' {
            // Preserve dotted path segments; kebab each segment
            // independently (e.g. `peerDependencyRules.ignoreMissing`
            // → `peer-dependency-rules.ignore-missing`).
            out.push(c);
            prev_lower = false;
        } else if c.is_ascii_uppercase() {
            if prev_lower {
                out.push('-');
            }
            out.push(c.to_ascii_lowercase());
            prev_lower = false;
        } else {
            out.push(c);
            prev_lower = c.is_ascii_lowercase() || c.is_ascii_digit();
        }
    }
    out
}

fn to_camel_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper_next = false;
    for c in s.chars() {
        if c == '-' {
            upper_next = true;
        } else if upper_next {
            out.push(c.to_ascii_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Escape a string as a valid Rust string literal using Debug formatting.
/// `{:?}` on a `&str` produces a quoted, escaped literal with `\"`, `\\`,
/// `\n`, etc. handled correctly — good enough for every field in
/// `settings.toml` today.
fn lit(s: &str) -> String {
    format!("{s:?}")
}

/// Format a `Vec<String>` as a Rust `&[&str]` literal.
fn slice_lit(items: &[String]) -> String {
    if items.is_empty() {
        return "&[]".to_string();
    }
    let parts: Vec<String> = items.iter().map(|s| lit(s)).collect();
    format!("&[{}]", parts.join(", "))
}
