//! Bake `data/build-jail-catalog.json` into the crate as `static` Rust.
//!
//! WHY CODEGEN RATHER THAN A RUNTIME PARSE. The catalog is fixed at compile time, so a
//! parse failure is a defect in the tree — not a condition the running jail should ever
//! have to handle. Emitting `&'static` literals means there is no runtime parse, no
//! fallible path to get wrong, and no way for a malformed catalog to reach a user: it
//! fails `cargo build`. `include_str!` + a lazy parse would instead defer the same defect
//! to first use, where the only honest responses are panic or silently jail-less grants.
//!
//! WHY THE VALIDATION LIVES HERE. Moving the tables from Rust literals to a data file
//! opens an editing surface a `static` did not have — a contributor can now write
//! `"siblingDirs": ["../../.."]` in JSON where the equivalent in Rust would have been
//! conspicuous. The checks below re-close that surface at the earliest possible moment,
//! so a catalog that would widen the jail cannot compile. They are deliberately
//! structural; the security RATIONALE (why a host is admissible at all) stays in the
//! crate's unit tests, which can express it against the compiled policy.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

const CATALOG: &str = "data/build-jail-catalog.json";

fn main() {
    println!("cargo:rerun-if-changed={CATALOG}");
    println!("cargo:rerun-if-changed=build.rs");

    let text = std::fs::read_to_string(CATALOG)
        .unwrap_or_else(|e| fail(&format!("cannot read {CATALOG}: {e}")));
    let catalog: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|e| fail(&format!("{CATALOG} is not valid JSON: {e}")));

    let out = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let out = Path::new(&out);
    emit(&out.join("download_hosts.rs"), &gen_hosts(&catalog));
    emit(&out.join("curated_grants.rs"), &gen_grants(&catalog));
    emit(
        &out.join("package_network.rs"),
        &gen_package_network(&catalog),
    );
}

fn emit(path: &Path, src: &str) {
    std::fs::write(path, src)
        .unwrap_or_else(|e| fail(&format!("cannot write {}: {e}", path.display())));
}

// ── $downloads ─────────────────────────────────────────────────────────────────

fn gen_hosts(catalog: &serde_json::Value) -> String {
    let entries = array(catalog, "networkHosts");
    let mut hosts = Vec::new();
    let mut seen = BTreeSet::new();

    for (i, entry) in entries.iter().enumerate() {
        let at = format!("networkHosts[{i}]");
        let host = string(entry, "host", &at);
        require_provenance(entry, &at);

        // Wildcard-freedom is the set's structural anti-exfiltration property: the proxy
        // resolves the name itself, so a `*.suffix` member would let a confined script put
        // chosen bytes in a DNS label and leak them without sending a payload.
        if host.contains('*') {
            fail(&format!(
                "{at}: `{host}` — $downloads must stay wildcard-free; a subdomain wildcard \
                 admits DNS-label exfiltration under the same hostname"
            ));
        }
        if host.is_empty() || host.contains('/') || host.contains(':') {
            fail(&format!("{at}: `{host}` is not a bare hostname"));
        }
        if !seen.insert(host.clone()) {
            fail(&format!("{at}: `{host}` is listed twice"));
        }
        hosts.push(host);
    }

    // The refused list is documentation, but a PR that moves an entry INTO the allowlist
    // while leaving its rejection rationale in place is a contradiction the reader would
    // have to resolve by guessing. Fail instead.
    for (i, entry) in array_at(catalog, &["notGranted", "hosts"])
        .iter()
        .enumerate()
    {
        let at = format!("notGranted.hosts[{i}]");
        let host = string(entry, "host", &at);
        string(entry, "reason", &at);
        string(entry, "detail", &at);
        // Held to the SAME provenance bar as an admitted host. A refusal is the input to a
        // later promotion decision, and an unevidenced one is worse than no entry: it reads
        // as a settled verdict while carrying nothing a reviewer could re-check.
        // `observedUrl` is the field a path-scoped grant would have to be written against.
        require_provenance(entry, &at);
        string(entry, "requester", &at);
        string(entry, "observedUrl", &at);
        if seen.contains(&host) {
            fail(&format!(
                "{at}: `{host}` is in networkHosts AND recorded as refused — one of the two \
                 is wrong"
            ));
        }
    }

    let mut src = String::from(
        "// @generated by build.rs from data/build-jail-catalog.json — do not edit.\n\
         /// The curated install-time artifact hosts — the build jail's egress allowlist and\n\
         /// the `$downloads` net token. Membership criteria, per-host provenance, and the\n\
         /// record of what was refused live in `data/build-jail-catalog.json`.\n\
         pub const DOWNLOAD_HOSTS: &[&str] = &[\n",
    );
    for host in &hosts {
        let _ = writeln!(src, "    {host:?},");
    }
    src.push_str("];\n");
    src
}

// ── the curated per-package grant table ────────────────────────────────────────

fn gen_grants(catalog: &serde_json::Value) -> String {
    let entries = array(catalog, "packageGrants");
    let mut seen = BTreeSet::new();
    let mut src = String::from(
        "// @generated by build.rs from data/build-jail-catalog.json — do not edit.\n\
         static CURATED_GRANTS: &[(&str, CuratedGrant)] = &[\n",
    );

    for (i, entry) in entries.iter().enumerate() {
        let at = format!("packageGrants[{i}]");
        let name = string(entry, "package", &at);
        require_provenance(entry, &at);
        string(entry, "mechanism", &at);
        if !seen.insert(name.clone()) {
            fail(&format!("{at}: `{name}` is listed twice"));
        }

        let siblings = opt_strings(entry, "siblingDirs", &at);
        for dir in &siblings {
            // A sibling grant names ONE entry of the package's own enclosing node_modules.
            // Anything with a separator or a traversal component is not a sibling — it is a
            // path out of the subtree the grant is bounded by.
            if dir.is_empty()
                || dir == "."
                || dir == ".."
                || dir.contains('/')
                || dir.contains('\\')
            {
                fail(&format!(
                    "{at}: siblingDirs entry `{dir}` must be a single directory NAME — a \
                     separator or traversal component escapes the enclosing node_modules \
                     the grant is bounded by"
                ));
            }
        }

        let reads = opt_strings(entry, "projectReads", &at);
        for rel in &reads {
            require_project_relative(rel, "projectReads", &at);
        }

        let writes = match entry.get("projectWrites") {
            None | Some(serde_json::Value::Null) => "ProjectWrites::None".to_string(),
            Some(w) => {
                let field = w
                    .get("manifestField")
                    .and_then(serde_json::Value::as_array)
                    .unwrap_or_else(|| {
                        fail(&format!(
                            "{at}: projectWrites must be {{\"manifestField\": [..]}} — the only \
                             shape the compiler implements"
                        ))
                    });
                if field.is_empty() {
                    fail(&format!(
                        "{at}: projectWrites.manifestField must name a field"
                    ));
                }
                let keys: Vec<String> = field
                    .iter()
                    .map(|k| {
                        k.as_str()
                            .unwrap_or_else(|| {
                                fail(&format!("{at}: manifestField entries must be strings"))
                            })
                            .to_string()
                    })
                    .collect();
                format!("ProjectWrites::ManifestField(&{keys:?})")
            }
        };

        let cwd = entry
            .get("projectCwd")
            .map(|v| {
                v.as_bool()
                    .unwrap_or_else(|| fail(&format!("{at}: projectCwd must be a boolean")))
            })
            .unwrap_or(false);

        let _ = write!(
            src,
            "    (\n        {name:?},\n        CuratedGrant {{\n            \
             sibling_dirs: &{siblings:?},\n            project_reads: &{reads:?},\n            \
             project_writes: {writes},\n            project_cwd: {cwd},\n        }},\n    ),\n"
        );
    }

    src.push_str("];\n");
    src
}

// ── the per-package egress table ───────────────────────────────────────────────

/// Which packages may reach the network under the build jail, as a NAME SET — the whole
/// per-package egress API. Egress is a per-package BOOLEAN: a catalog entry means the grant
/// was ratified by review, and how much network the package then uses is not something this
/// table narrows.
///
/// WHY NO HOST LISTS. Per-host permissioning was evaluated against the real catalog and
/// dropped: a redirect is a SECOND connection to a SECOND host, so an allowlist naming only
/// the origin denies the download at the second hop, and an upstream moving its CDN silently
/// breaks a package a host list claimed to permit. The boolean cannot fail that way, and the
/// threat it answers — an unvetted package with a newly published hook — is not addressed by
/// narrowing a package somebody already reviewed.
///
/// TWO SOURCES, ONE VERDICT, because a grant can be spelled either way and both mean "on":
///  - `networkHosts[].fetchedBy` — a package named as fetching an admitted host.
///  - `packageNetwork.full` — a package whose host set was never enumerable in the first place.
///
/// `notGranted.packages` OVERRIDES both. A package refused on the merits gets nothing, and it
/// can legitimately appear in `fetchedBy` as an observation of what it *did* fetch — recording
/// the observation must not become a grant. (Real case: `install-peers` is both.)
///
/// Every key is OPTIONAL: this branch's catalog carries only the inversion source, and the
/// per-package-egress catalog lane owns `packageNetwork.full` / `notGranted.packages`. Absent
/// ⇒ absent from the allow set, which is the conservative direction.
fn gen_package_network(catalog: &serde_json::Value) -> String {
    let refused: BTreeSet<String> = array_at(catalog, &["notGranted", "packages"])
        .iter()
        .enumerate()
        .map(|(i, e)| string(e, "package", &format!("notGranted.packages[{i}]")))
        .collect();

    let mut allowed: BTreeSet<String> = BTreeSet::new();
    for entry in array(catalog, "networkHosts") {
        for pkg in opt_strings(entry, "fetchedBy", "networkHosts") {
            allowed.insert(pkg);
        }
    }
    for (i, entry) in array_at(catalog, &["packageNetwork", "full"])
        .iter()
        .enumerate()
    {
        let at = format!("packageNetwork.full[{i}]");
        require_provenance(entry, &at);
        allowed.insert(string(entry, "package", &at));
    }
    for name in &refused {
        allowed.remove(name);
    }

    let mut src = String::from(
        "// @generated by build.rs from data/build-jail-catalog.json — do not edit.\n\
         /// Packages whose build scripts MAY reach the network, as the union of\n\
         /// `networkHosts[].fetchedBy` and `packageNetwork.full` minus\n\
         /// `notGranted.packages`. Sorted, so the lookup may binary-search.\n\
         pub const PACKAGE_NETWORK_ALLOWED: &[&str] = &",
    );
    let _ = writeln!(src, "{:?};", allowed.iter().collect::<Vec<_>>());
    src
}

/// A project-relative subtree, checked before the runtime clamp ever sees it. The clamp in
/// `curated::contained` is the enforcing check and stays; this one turns a traversal that
/// the clamp would silently DROP into a visible build failure, so a contributor learns the
/// grant does not work instead of shipping one that quietly does nothing.
fn require_project_relative(rel: &str, field: &str, at: &str) {
    let p = Path::new(rel);
    if rel.is_empty() || p.is_absolute() || rel.starts_with('/') || rel.starts_with('\\') {
        fail(&format!(
            "{at}: {field} entry `{rel}` must be project-relative"
        ));
    }
    if p.components()
        .any(|c| matches!(c, std::path::Component::ParentDir))
    {
        fail(&format!(
            "{at}: {field} entry `{rel}` traverses out of the project root"
        ));
    }
}

/// Every entry carries how it was learned. This is what lets a later reader tell a grant
/// measured against a real denial from one taken on a vendor's word — the two are not
/// equally strong, and the catalog would lose that distinction the moment an entry could
/// be added without stating it.
fn require_provenance(entry: &serde_json::Value, at: &str) {
    const KINDS: &[&str] = &["measured", "vendor-documented", "source-read"];
    let evidence = string(entry, "evidence", at);
    if !KINDS.contains(&evidence.as_str()) {
        fail(&format!(
            "{at}: evidence `{evidence}` is not one of {KINDS:?}"
        ));
    }
    if string(entry, "observed", at).len() < 20 {
        fail(&format!(
            "{at}: `observed` must state what was actually seen, not a placeholder"
        ));
    }
    string(entry, "platform", at);
}

// ── helpers ────────────────────────────────────────────────────────────────────

fn array<'a>(catalog: &'a serde_json::Value, key: &str) -> &'a Vec<serde_json::Value> {
    catalog
        .get(key)
        .and_then(serde_json::Value::as_array)
        .unwrap_or_else(|| fail(&format!("{CATALOG}: `{key}` must be an array")))
}

fn array_at<'a>(catalog: &'a serde_json::Value, path: &[&str]) -> &'a [serde_json::Value] {
    let mut node = catalog;
    for key in path {
        match node.get(key) {
            Some(next) => node = next,
            None => return &[],
        }
    }
    node.as_array()
        .map(Vec::as_slice)
        .unwrap_or_else(|| fail(&format!("{CATALOG}: `{}` must be an array", path.join("."))))
}

fn string(entry: &serde_json::Value, key: &str, at: &str) -> String {
    entry
        .get(key)
        .and_then(serde_json::Value::as_str)
        .map(str::to_string)
        .filter(|s| !s.trim().is_empty())
        .unwrap_or_else(|| {
            fail(&format!(
                "{at}: `{key}` is required and must be a non-empty string"
            ))
        })
}

fn opt_strings(entry: &serde_json::Value, key: &str, at: &str) -> Vec<String> {
    match entry.get(key) {
        None | Some(serde_json::Value::Null) => Vec::new(),
        Some(v) => v
            .as_array()
            .unwrap_or_else(|| fail(&format!("{at}: `{key}` must be an array of strings")))
            .iter()
            .map(|s| {
                s.as_str()
                    .unwrap_or_else(|| fail(&format!("{at}: `{key}` entries must be strings")))
                    .to_string()
            })
            .collect(),
    }
}

fn fail(msg: &str) -> ! {
    // Printed as a cargo error so it surfaces at the top of the build output rather than
    // buried in a panic backtrace.
    println!("cargo:warning={msg}");
    panic!("build-jail catalog is invalid — {msg}");
}
