//! Bake `data/build-jail-catalog.json` into the crate as `static` Rust.
//!
//! WHY CODEGEN RATHER THAN A RUNTIME PARSE. The catalog is fixed at compile time, so a
//! parse failure is a defect in the tree — not a condition the running jail should ever
//! have to handle. Emitting `&'static` literals means there is no runtime parse, no
//! fallible path to get wrong, and no way for a malformed catalog to reach a user: it
//! fails `cargo build`. `include_str!` + a lazy parse would instead defer the same defect
//! to first use, where the only honest responses are panic or silently jail-less grants.
//!
//! WHERE THE VALIDATION LIVES, and why not here. Moving the tables from Rust literals to a
//! data file opened an editing surface a `static` did not have — a contributor can now write
//! `"siblingDirs": ["../../.."]` in JSON where the equivalent in Rust would have been
//! conspicuous. The checks that re-close that surface live in `src/catalog.rs`, pulled in
//! below with `#[path]`, because the dev-only runtime override has to run the SAME ones at
//! load time and a second copy would drift. This build script's remaining job is codegen:
//! parse via the shared validator, fail the build on `Err`, emit `&'static` literals.

#[path = "src/catalog.rs"]
mod catalog;

use std::fmt::Write as _;
use std::path::Path;

const CATALOG: &str = "data/build-jail-catalog.json";

fn main() {
    println!("cargo:rerun-if-changed={CATALOG}");
    println!("cargo:rerun-if-changed=build.rs");
    // The validator is a separate file now, so a change to it must re-run this script.
    println!("cargo:rerun-if-changed=src/catalog.rs");

    let text = std::fs::read_to_string(CATALOG)
        .unwrap_or_else(|e| fail(&format!("cannot read {CATALOG}: {e}")));
    let catalog = catalog::parse(&text).unwrap_or_else(|e| fail(&format!("{CATALOG}: {e}")));

    let out = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let out = Path::new(&out);
    emit(&out.join("download_hosts.rs"), &gen_hosts(&catalog));
    emit(&out.join("curated_grants.rs"), &gen_grants(&catalog));
    emit(
        &out.join("package_network.rs"),
        &gen_package_network(&catalog),
    );
}

fn emit(path: &Path, src: &str) {
    std::fs::write(path, src)
        .unwrap_or_else(|e| fail(&format!("cannot write {}: {e}", path.display())));
}

fn gen_hosts(catalog: &catalog::Catalog) -> String {
    let mut src = String::from(
        "// @generated by build.rs from data/build-jail-catalog.json — do not edit.\n\
         /// The curated install-time artifact hosts — the build jail's egress allowlist and\n\
         /// the `$downloads` net token. Membership criteria, per-host provenance, and the\n\
         /// record of what was refused live in `data/build-jail-catalog.json`.\n\
         pub const DOWNLOAD_HOSTS: &[&str] = &[\n",
    );
    for host in &catalog.download_hosts {
        let _ = writeln!(src, "    {host:?},");
    }
    src.push_str("];\n");
    src
}

fn gen_grants(catalog: &catalog::Catalog) -> String {
    let mut src = String::from(
        "// @generated by build.rs from data/build-jail-catalog.json — do not edit.\n\
         static CURATED_GRANTS: &[(&str, CuratedGrant)] = &[\n",
    );

    for grant in &catalog.package_grants {
        let name = &grant.package;
        let siblings = &grant.sibling_dirs;
        let reads = &grant.project_reads;
        let cwd = grant.project_cwd;
        let writes = match &grant.project_writes {
            None => "ProjectWrites::None".to_string(),
            Some(keys) => format!("ProjectWrites::ManifestField(&{keys:?})"),
        };
        let _ = write!(
            src,
            "    (\n        {name:?},\n        CuratedGrant {{\n            \
             sibling_dirs: &{siblings:?},\n            project_reads: &{reads:?},\n            \
             project_writes: {writes},\n            project_cwd: {cwd},\n        }},\n    ),\n"
        );
    }

    src.push_str("];\n");
    src
}

fn gen_package_network(catalog: &catalog::Catalog) -> String {
    let mut src = String::from(
        "// @generated by build.rs from data/build-jail-catalog.json — do not edit.\n\
         /// Packages whose build scripts MAY reach the network, as the union of\n\
         /// `networkHosts[].fetchedBy` and `packageNetwork.full` minus\n\
         /// `notGranted.packages`. Sorted, so the lookup may binary-search.\n\
         pub const PACKAGE_NETWORK_ALLOWED: &[&str] = &",
    );
    let _ = writeln!(src, "{:?};", catalog.package_network_allowed);
    src
}

fn fail(msg: &str) -> ! {
    // Printed as a cargo error so it surfaces at the top of the build output rather than
    // buried in a panic backtrace.
    println!("cargo:warning={msg}");
    panic!("build-jail catalog is invalid — {msg}");
}
