//! The run-time half of `--external`.
//!
//! Leaving a package out of the bundle is only half the feature. A compiled
//! artifact runs its bundle from nub's cache directory, so Node's own bare-
//! specifier walk starts there and finds nothing — an externalized package would
//! be unresolvable on EVERY machine, including one that has it installed. So the
//! artifact carries a resolve hook that re-bases those specifiers onto the
//! directory the executable was started in, which is the only base with a
//! meaning the user can act on ("install it where you run it").
//!
//! The hook cannot be installed by the bundle itself: Node links a module's
//! entire static import graph before running any of its code, so a hook the
//! bundle registered would arrive after its own imports had already been
//! resolved. Hence the generated wrapper — it registers the hook, then reaches
//! the bundle through `import()`, which resolves at call time.
//!
//! This lives in `compile`, not `bundle`, on purpose: `nub build` emits a file
//! into a real project where Node's ordinary resolution already does the right
//! thing, so it wants the bundler flag WITHOUT this shim.

use anyhow::{Result, bail};
use nub_core::node::version::NodeVersion;

/// The generated wrapper, and the artifact's new entry.
const WRAPPER: &str = "__nub_entry.mjs";
/// The generated hook module.
const HOOK: &str = "__nub_external.mjs";

/// `module.registerHooks` — a synchronous resolve hook, no loader worker and no
/// experimental warning — landed in Node 22.15, the same floor nub's own fast
/// tier uses. Below it the shim has nothing to register with.
fn min_node() -> NodeVersion {
    NodeVersion::new(22, 15, 0)
}

/// Reject `--external` against a Node the shim cannot run on, BEFORE the ~100 MB
/// runtime download. `version` is the exact embedded version, or (under
/// `--smol`) the floor the launcher refuses to start below — so in both shapes
/// it is a lower bound on what will actually run the artifact. `source` names
/// where that version came from, because a bare major pin floors at `X.0.0` and
/// the refusal is otherwise baffling on a machine running a newer X.
pub fn check_node_support(version: &NodeVersion, source: &str, external: &[String]) -> Result<()> {
    if external.is_empty() || *version >= min_node() {
        return Ok(());
    }
    bail!(
        "--external needs Node {} or newer, and this build targets Node {version} \
         (from {source}).\n\
         \x20\x20An externalized package is resolved by a hook the artifact installs at\n\
         \x20\x20startup (module.registerHooks), which older Node does not have.\n\
         \x20\x20Pass --target {} (or newer), or drop --external and let the package be\n\
         \x20\x20bundled.",
        min_node(),
        min_node()
    )
}

/// Defines that keep the wrapper invisible to the code it runs.
///
/// The bundle stops being the process entry point once the wrapper is in front
/// of it, so Node reports `import.meta.main === false` inside it — a silent
/// wrong answer that makes an `if (import.meta.main) main();` program do
/// nothing, with no error to attribute. The bundle IS the program (the wrapper
/// imports nothing else), and a bundle without `--external` already sees `true`,
/// so pinning it restores the untouched behavior rather than inventing one.
pub fn entry_defines(external: &[String]) -> Vec<(String, String)> {
    if external.is_empty() {
        return Vec::new();
    }
    vec![("import.meta.main".into(), "true".into())]
}

/// The generated entry name, plus the two files to add to the payload.
pub struct Shim {
    pub entry: String,
    pub files: Vec<(String, Vec<u8>)>,
}

/// Build the wrapper + hook for `packages`, entering the real bundle at `entry`.
/// `app_files` is the payload the shim will be appended to — the launcher writes
/// those files by name, so a collision would silently overwrite a bundle chunk.
pub fn shim(app_files: &[(String, Vec<u8>)], entry: &str, packages: &[String]) -> Result<Shim> {
    if let Some((name, _)) = app_files.iter().find(|(n, _)| n == WRAPPER || n == HOOK) {
        bail!("the bundle already emits a file named {name}, which --external needs for its shim");
    }
    let list = serde_json::to_string(packages)?;
    let target = serde_json::to_string(&format!("./{entry}"))?;

    let hook = format!(
        r#"// Generated by `nub compile --external`. Resolves the externalized packages
// from the directory this executable was started in — the bundle itself runs
// from a cache directory, where nothing would ever be found.
import {{ registerHooks, createRequire }} from "node:module";
import {{ pathToFileURL }} from "node:url";
import {{ join }} from "node:path";

const PACKAGES = {list};

// Only the BUNDLE's imports are re-based. Once an external is resolved, what it
// imports in turn resolves normally from its own location — re-basing those too
// would let a package's internal subpath import land in a different copy.
const APP = new URL("./", import.meta.url).href;
// A directory URL, so Node's own "Cannot find package X imported from …" names
// the directory it searched rather than a placeholder file that does not exist.
const BASE = new URL("./", pathToFileURL(join(process.cwd(), "x"))).href;
// Node's CJS resolver ignores a substituted parentURL and re-bases on the
// requiring module's real path, so a createRequire() call inside the bundle
// would resolve against the cache dir and fail. Verified 2026-07-29 on Node
// 24.18: the ESM path honors the substitution, the CJS path does not.
const requireFromBase = createRequire(new URL("x", BASE));

// Mirrors is_package_specifier() in compile/bundle.rs: the package, or a subpath
// of it. The two rules must agree, or a specifier is dropped from the bundle and
// then not redirected.
const owner = (specifier) =>
  PACKAGES.find((p) => specifier === p || specifier.startsWith(p + "/"));

registerHooks({{
  resolve(specifier, context, nextResolve) {{
    const pkg = context.parentURL?.startsWith(APP) ? owner(specifier) : undefined;
    if (pkg === undefined) return nextResolve(specifier, context);
    try {{
      return nextResolve(specifier, {{ ...context, parentURL: BASE }});
    }} catch (cause) {{
      try {{
        return {{
          url: pathToFileURL(requireFromBase.resolve(specifier)).href,
          shortCircuit: true,
        }};
      }} catch {{}}
      // "Install it" is only the right advice for a package that is absent. An
      // installed package with an unexported subpath or a malformed specifier
      // fails here too, and mislabelling that would send the user hunting for a
      // dependency they already have.
      if (cause?.code !== "ERR_MODULE_NOT_FOUND" && cause?.code !== "MODULE_NOT_FOUND") throw cause;
      const err = new Error(
        `Cannot find ${{specifier}}.\n\n` +
          `  This executable was compiled with --external ${{pkg}}, so ${{pkg}} is not\n` +
          `  part of it — it is resolved when the executable runs, from the directory\n` +
          `  it is started in.\n\n` +
          `  Started in: ${{process.cwd()}}\n` +
          `  Install ${{pkg}} there, or run this from a directory that already has it.`,
        {{ cause }},
      );
      err.code = "ERR_NUB_EXTERNAL_NOT_FOUND";
      throw err;
    }}
  }},
}});
"#
    );

    let wrapper = format!(
        r#"// Generated by `nub compile --external`. Node resolves a module's whole static
// import graph before running any of its code, so the hook has to be installed
// from OUTSIDE the bundle and the bundle reached through import().
import {{ fileURLToPath }} from "node:url";
import "./{HOOK}";

// The wrapper is an implementation detail; argv[1] stays the real entry so the
// `import.meta.url === pathToFileURL(process.argv[1]).href` main-module idiom
// keeps working.
process.argv[1] = fileURLToPath(new URL({target}, import.meta.url));
await import({target});
"#
    );

    Ok(Shim {
        entry: WRAPPER.to_string(),
        files: vec![
            (HOOK.to_string(), hook.into_bytes()),
            (WRAPPER.to_string(), wrapper.into_bytes()),
        ],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app(names: &[&str]) -> Vec<(String, Vec<u8>)> {
        names
            .iter()
            .map(|n| ((*n).to_string(), Vec::new()))
            .collect()
    }

    fn built(packages: &[&str]) -> Shim {
        let packages: Vec<String> = packages.iter().map(|p| (*p).to_string()).collect();
        shim(&app(&["app.js"]), "app.js", &packages).expect("shim")
    }

    fn file<'a>(s: &'a Shim, name: &str) -> &'a str {
        let bytes = &s
            .files
            .iter()
            .find(|(n, _)| n == name)
            .unwrap_or_else(|| panic!("the shim must emit {name}, got {:?}", s.files))
            .1;
        std::str::from_utf8(bytes).expect("utf8")
    }

    #[test]
    fn the_node_gate_fires_only_when_a_package_is_externalized() {
        let old = NodeVersion::new(20, 19, 0);
        let ok = NodeVersion::new(22, 15, 0);
        assert!(check_node_support(&old, "--target", &[]).is_ok());
        assert!(check_node_support(&ok, "--target", &["prettier".into()]).is_ok());

        let err = check_node_support(&old, ".node-version", &["prettier".into()])
            .expect_err("must be rejected");
        let msg = format!("{err:#}");
        assert!(msg.contains("22.15.0"), "must name the floor: {msg}");
        assert!(
            msg.contains("20.19.0"),
            "must name what was targeted: {msg}"
        );
        assert!(
            msg.contains(".node-version"),
            "must name where that version came from, or a major-pin floor looks \
             arbitrary: {msg}"
        );
        assert!(msg.contains("--target"), "must name the way out: {msg}");
    }

    // The wrapper is what puts the hook in front of the bundle's own imports, so
    // it must reach the bundle through import() and not a static import.
    #[test]
    fn the_wrapper_registers_the_hook_before_it_imports_the_bundle() {
        let s = built(&["prettier", "@scope/pkg"]);
        assert_eq!(s.entry, "__nub_entry.mjs");
        let wrapper = file(&s, "__nub_entry.mjs");
        assert!(
            wrapper.contains(r#"import "./__nub_external.mjs""#),
            "the hook must be a static import, so it evaluates first: {wrapper}"
        );
        assert!(
            wrapper.contains(r#"await import("./app.js")"#),
            "the bundle must be reached dynamically, after the hook: {wrapper}"
        );
        assert!(
            file(&s, "__nub_external.mjs").contains(r#"["prettier","@scope/pkg"]"#),
            "the package list must be baked in as JSON"
        );
    }

    // Both files are assembled by `format!` with brace escaping, so a syntax
    // error would ship as a runtime crash inside a frozen binary with no build
    // signal at all. Parsing them is what makes that class impossible.
    #[test]
    fn both_generated_files_are_valid_esm() {
        let s = built(&["prettier", "@scope/pkg"]);
        for (name, bytes) in &s.files {
            let source = std::str::from_utf8(bytes).expect("utf8");
            let allocator = oxc_allocator::Allocator::default();
            let parsed =
                oxc_parser::Parser::new(&allocator, source, oxc_span::SourceType::mjs()).parse();
            assert!(
                !parsed.panicked && parsed.diagnostics.is_empty(),
                "{name} must parse as ESM, got {:?}\n{source}",
                parsed.diagnostics
            );
        }
    }

    #[test]
    fn a_bundle_file_named_like_the_shim_is_refused_rather_than_overwritten() {
        let pkgs = vec!["prettier".to_string()];
        assert!(shim(&app(&["__nub_entry.mjs"]), "__nub_entry.mjs", &pkgs).is_err());
        // Not the entry, but still a collision the launcher would resolve by
        // overwriting one of the two.
        assert!(shim(&app(&["app.js", "__nub_external.mjs"]), "app.js", &pkgs).is_err());
    }
}
