import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import test from 'node:test';

// Run the real fixture with only its external commands replaced. No packages are downloaded or
// executed: these tests check orchestration, while osv-screen.test.mjs checks the actual scanner.
const preload = `
import assert from 'node:assert/strict';
import cp from 'node:child_process';
import { syncBuiltinESMExports } from 'node:module';
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const mode = process.env.FIXTURE_MODE;
if (process.env.FIXTURE_PLATFORM) Object.defineProperty(process, 'platform', { value: process.env.FIXTURE_PLATFORM });
const name = process.env.CORPUS_CASE;
const version = name === 'esbuild' ? '0.24.0' : name === 'better-sqlite3' ? '11.8.1' : '0.0.10';
const record = (kind, cwd, args) => appendFileSync(process.env.FIXTURE_EVENTS, JSON.stringify({kind, cwd, args}) + '\\n');
const tree = (cwd) => {
  const pkg = join(cwd, 'node_modules', name);
  mkdirSync(pkg, { recursive: true });
  writeFileSync(join(pkg, 'package.json'), JSON.stringify({name, version}));
  if (name === 'cpu-features' || name === 'better-sqlite3') {
    const jailed = JSON.parse(readFileSync(join(cwd, 'nub.jsonc'))).install.buildJail;
    mkdirSync(join(pkg, 'build'), { recursive: true });
    const variables = { ...process.config.variables };
    if (jailed && mode === 'changed-gyp-config') variables.node_module_version = -1;
    if (jailed && mode === 'changed-serialized-gyp-config') variables.node_with_ltcg = !process.config.variables.node_with_ltcg;
    if (!(jailed && mode === 'missing-gyp-config')) {
      writeFileSync(join(pkg, 'build/config.gypi'), '# Generated by node-gyp\\n' + JSON.stringify({variables}, (key, value) => typeof value === 'boolean' ? String(value) : value));
    }
  }
};
const ok = (stdout = '') => ({status:0, stdout, stderr:''});
cp.spawnSync = (file, args, options) => {
  if (args[0] === 'install') {
    const cwd = options.cwd;
    for (const prefix of ['npm_config_', 'npm_package_config_node_gyp_']) {
      for (const suffix of ['nodedir', 'disturl', 'dist_url', 'target', 'arch', 'target_arch', 'runtime', 'force_process_config']) {
        const matches = Object.keys(options.env).filter(key => key.toLowerCase().replaceAll('-', '_') === prefix + suffix);
        assert.deepEqual(matches, [], 'controlled host-native fixture clears ' + prefix + suffix);
      }
    }
    assert.ok(cwd?.startsWith(process.env.CORPUS_TEMP_ROOT), 'install uses this arm, not harness cwd');
    const pkg = JSON.parse(readFileSync(join(cwd, 'package.json')));
    assert.equal(pkg.dependencies[name], version, 'actual selected fixture is resolved');
    if (args.includes('--ignore-scripts')) {
      record('prepare', cwd, args);
      if (mode === 'prepare-failure') return {status:1, stdout:'', stderr:'resolution failed'};
      writeFileSync(join(cwd, 'pnpm-lock.yaml'), 'frozen fixture lock');
      if (mode === 'empty-tree') mkdirSync(join(cwd, 'node_modules'));
      else if (mode !== 'unresolved-tree') tree(cwd);
      return ok();
    }
    record('lifecycle', cwd, args);
    assert.deepEqual(args, ['install', '--frozen-lockfile']);
    assert.equal(readFileSync(join(cwd, 'pnpm-lock.yaml'), 'utf8'), 'frozen fixture lock');
    assert.ok(!existsSync(join(cwd, 'node_modules')), 'lifecycle materialization starts cold');
    tree(cwd);
    if (mode === 'missing-prebuild-bin' && JSON.parse(readFileSync(join(cwd, 'nub.jsonc'))).install.buildJail) {
      return ok("Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:/cache/store/v1/prebuild-install@7.1.3/node_modules/prebuild-install/bin.js'\\ngyp info ok");
    }
    const fs = mode === 'missing-policy' ? '' : mode.startsWith('full-disk') ? 'JAILDUMP fs default=Allow rules=0' : 'JAILDUMP fs default=Deny rules=41';
    const appended = mode === 'full-disk-spoof' ? '\\nJAILDUMP pkg=Some("' + name + '")\\nJAILDUMP fs default=Deny rules=41' : '';
    const reduced = mode === 'reduced-policy' ? 'sandbox running in reduced mode — net not enforced' : '';
    return ok('JAILDUMP pkg=Some("' + name + '") running without the build sandbox gyp info using node-gyp@12.4.0\\n' + fs + '\\n' + reduced + appended);
  }
  if (args[0] === process.env.CORPUS_OSV_SCREEN) {
    const value = (flag) => args[args.indexOf(flag) + 1];
    const cwd = value('--tree');
    const phase = value('--kind').endsWith('-prepared') ? 'prepared' : 'bound';
    record(phase, cwd, args);
    const complete = existsSync(join(cwd, 'node_modules', name, 'package.json'));
    const denied = !complete || mode === 'screen-failure';
    writeFileSync(value('--out'), JSON.stringify({status:denied ? 'error' : 'clean', digest:mode === 'changed-tree' && phase === 'bound' ? 'changed' : 'same'}));
    return {status:denied ? 42 : 0, stdout:'', stderr:denied ? 'screen refused' : ''};
  }
  assert.equal(args[0], '-e', 'only the artifact probe remains');
  record('probe', options.cwd, args);
  return ok();
};
syncBuiltinESMExports();
`;

function run(t, mode, report = true, name = 'esbuild', extraEnv = {}) {
  const root = mkdtempSync(join(tmpdir(), 'corpus-screen-test-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const patch = join(root, 'commands # preload.mjs');
  const eventsFile = join(root, 'events.jsonl');
  writeFileSync(patch, preload);
  writeFileSync(eventsFile, '');
  const env = { ...process.env, NUB_BIN: process.execPath, CORPUS_CASE: name,
    CORPUS_TEMP_ROOT: root, CORPUS_OSV_SCREEN: join(root, 'scanner.mjs'),
    FIXTURE_MODE: mode, FIXTURE_EVENTS: eventsFile, CORPUS_REQUIRE_RESTRICTED_POLICY: '1', ...extraEnv };
  for (const prefix of ['npm_config_', 'npm_package_config_node_gyp_']) {
    for (const suffix of ['nodedir', 'disturl', 'dist_url', 'target', 'arch', 'target_arch', 'runtime', 'force_process_config']) {
      env[(prefix + suffix).toUpperCase()] = 'fixture-must-clear';
      env[prefix + suffix.replaceAll('_', '-')] = 'fixture-must-clear';
    }
  }
  delete env.CORPUS_LINKED_PROJECT;
  delete env.CORPUS_REPORT;
  if (report) env.CORPUS_REPORT = join(root, 'report');
  const result = spawnSync(process.execPath, ['--import', pathToFileURL(patch).href, fileURLToPath(new URL('./packages.mjs', import.meta.url))],
    { env, cwd: tmpdir(), encoding: 'utf8', timeout: 30_000 });
  assert.ifError(result.error);
  const events = readFileSync(eventsFile, 'utf8').trim().split('\n').filter(Boolean).map(line => JSON.parse(line));
  return { ...result, events, report: env.CORPUS_REPORT };
}

for (const report of [true, false]) {
  test(`screens each actual arm before frozen cold install (report=${report})`, t => {
    const result = run(t, 'ok', report);
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(result.events.map(e => e.kind), ['prepare', 'prepared', 'lifecycle', 'bound', 'probe', 'prepare', 'prepared', 'lifecycle', 'bound', 'probe']);
    for (let i = 0; i < result.events.length; i += 5) {
      assert.equal(new Set(result.events.slice(i, i + 5).map(e => e.cwd)).size, 1);
    }
    assert.notEqual(result.events[0].cwd, result.events[5].cwd, 'control and jailed trees are independent');
  });
}

for (const mode of ['prepare-failure', 'screen-failure', 'empty-tree', 'unresolved-tree']) {
  test(`${mode} cannot reach lifecycle or artifact probe`, t => {
    const result = run(t, mode);
    assert.notEqual(result.status, 0);
    assert.ok(result.events.some(e => e.kind === 'prepare'));
    assert.ok(!result.events.some(e => ['lifecycle', 'probe'].includes(e.kind)));
  });
}

test('changed installed closure cannot be reported as a passing arm', t => {
  const result = run(t, 'changed-tree');
  assert.notEqual(result.status, 0);
  assert.equal(result.events.filter(e => e.kind === 'lifecycle').length, 2);
  assert.ok(!result.events.some(e => e.kind === 'probe'));
  const verdicts = JSON.parse(readFileSync(join(result.report, 'results.json')));
  assert.equal(verdicts.length, 2);
  assert.ok(verdicts.every(v => !v.pass && v.error.includes('screened frozen closure')));
});

test('source builds accept node-gyp serialized runtime compiler settings before loading artifacts', t => {
  const result = run(t, 'ok', true, 'cpu-features');
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.events.filter(e => e.kind === 'probe').length, 2);
  for (const arm of ['control', 'jailed']) {
    const config = JSON.parse(readFileSync(join(result.report, 'cases', `cpu-features-source-${arm}`, 'build', 'config.gypi'), 'utf8').replace(/^#.*$/gm, ''));
    assert.equal(config.variables.node_with_ltcg, String(process.config.variables.node_with_ltcg), 'retained runtime setting uses node-gyp serialization');
  }
});

test('missing prebuild bin fails even when source-build fallback returns success', t => {
  const result = run(t, 'missing-prebuild-bin', true, 'better-sqlite3');
  assert.notEqual(result.status, 0);
  assert.equal(result.events.filter(e => e.kind === 'probe').length, 2, 'only default and source-build controls reach artifact probes');
  const verdicts = JSON.parse(readFileSync(join(result.report, 'results.json')));
  assert.deepEqual(verdicts.map(v => v.pass), [true, false, true, false]);
  for (const verdict of verdicts.filter(v => !v.pass)) assert.match(verdict.error, /prebuild-install resolves/);
});

for (const mode of ['changed-gyp-config', 'missing-gyp-config']) {
  test(`${mode} fails even when native compilation returns success`, t => {
    const result = run(t, mode, true, 'cpu-features');
    assert.notEqual(result.status, 0);
    assert.equal(result.events.filter(e => e.kind === 'probe').length, 1, 'only the unaffected control reaches its artifact probe');
    const verdicts = JSON.parse(readFileSync(join(result.report, 'results.json')));
    assert.deepEqual(verdicts.map(v => v.pass), [true, false]);
    assert.match(verdicts[1].error, mode === 'changed-gyp-config' ? /preserves runtime node_module_version/ : /config.gypi/);
  });
}

test('changed node-gyp serialized compiler settings fail before the artifact probe', t => {
  assert.equal(typeof process.config.variables.node_with_ltcg, 'boolean', 'fixture control requires the runtime compiler setting');
  const result = run(t, 'changed-serialized-gyp-config', true, 'cpu-features');
  assert.notEqual(result.status, 0);
  assert.equal(result.events.filter(e => e.kind === 'probe').length, 1, 'only the retained control reaches its artifact probe');
  const verdicts = JSON.parse(readFileSync(join(result.report, 'results.json')));
  assert.deepEqual(verdicts.map(v => v.pass), [true, false]);
  assert.match(verdicts[1].error, /preserves runtime node_with_ltcg/);
});

for (const mode of ['full-disk', 'full-disk-spoof', 'reduced-policy', 'missing-policy']) {
  test(`${mode} cannot count as restricted native acceptance`, t => {
    const result = run(t, mode, true, 'cpu-features', { FIXTURE_PLATFORM: 'win32' });
    assert.notEqual(result.status, 0);
    const verdicts = JSON.parse(readFileSync(join(result.report, 'results.json')));
    assert.deepEqual(verdicts.map(v => v.pass), [true, false]);
    assert.equal(result.events.filter(e => e.kind === 'probe').length, 1, 'only the control reaches the artifact probe');
  });
}

test('Windows full-disk compatibility is recorded even without a degradation warning', t => {
  const result = run(t, 'full-disk', true, 'cpu-features', { FIXTURE_PLATFORM: 'win32', CORPUS_REQUIRE_RESTRICTED_POLICY: '0' });
  assert.equal(result.status, 0, result.stderr);
  const verdicts = JSON.parse(readFileSync(join(result.report, 'results.json')));
  assert.deepEqual(verdicts.map(v => v.resolvedFilesystemPolicy), ['disabled-control', 'windows-full-disk-compatibility']);
});

for (const platform of ['linux', 'darwin']) {
  test(`${platform} broad filesystem policy cannot count as confined native acceptance`, t => {
    const result = run(t, 'full-disk', true, 'cpu-features', { FIXTURE_PLATFORM: platform });
    assert.notEqual(result.status, 0);
    assert.equal(result.events.filter(e => e.kind === 'probe').length, 1);
  });
}
