//! Per-package egress: which dependency may reach the network under the build jail.
//!
//! # The defense is PACKAGE IDENTITY, and it is a BOOLEAN
//!
//! This is the load-bearing premise and it is easy to get backwards. The attack the build jail
//! exists to blunt is the one Shai-Hulud used: an attacker publishes a new `postinstall` into a
//! package that never had one, and it runs with the user's full access. That package is not one
//! anybody vetted for network use — it is `chalk`, or whatever the worm reached.
//!
//! So the control that matters is the ENTRY, not the hostname. A package with no entry gets no
//! egress; a package that needs egress arrives through a pull request against
//! `data/build-jail-catalog.json`, and that PR is the whole opt-in mechanism. A package the
//! catalog admitted gets the network — possibly all of it — because the grant was ratified by
//! the review that added it.
//!
//! # Why there is no host list
//!
//! Per-host permissioning was evaluated against the real catalog and dropped. It is the
//! fragile half: a redirect is a SECOND connection to a SECOND host, so an allowlist naming
//! only the origin denies the download at the second hop, and an upstream moving its CDN
//! silently breaks a package the list claimed to permit. The boolean cannot fail either way.
//! It also buys little — narrowing hosts constrains a package somebody already reviewed, and
//! does nothing about the unvetted one, which is the actual threat.
//!
//! # Enforcement is USERLAND and reaches Node children only
//!
//! [`crate::net_gate_node_options`] is what enforces this table, and it is a `--import` preload
//! inside the confined Node, not an OS boundary. See that function for the honest bound.

// THE TABLE IS DATA, NOT CODE. Generated by `build.rs` as the union of
// `networkHosts[].fetchedBy` and `packageNetwork.full` minus `notGranted.packages` — the host
// entries already record which packages fetch them, so a package-first restatement would be a
// second source free to drift.
include!(concat!(env!("OUT_DIR"), "/package_network.rs"));

/// Whether `package_name`'s build scripts may reach the network.
///
/// `None` — aube withheld the installer-resolved identity because its root is a checkout it
/// FETCHED — is `false`, the conservative direction and the same reading the curated filesystem
/// table takes.
///
/// The lookup is EXACT on the resolver-assigned name, which is what stops a dependency from
/// renaming itself into an entry.
pub fn build_jail_net_allowed(package_name: Option<&str>) -> bool {
    package_name.is_some_and(|name| PACKAGE_NETWORK_ALLOWED.binary_search(&name).is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The authorship invariant: the key is the name the RESOLVER assigned and the lookup is
    /// exact, so a package cannot reach an entry by renaming itself into its neighbourhood.
    /// `None` and an unlisted name are both denied — the default that IS the mechanism.
    #[test]
    fn no_entry_means_no_network_and_a_near_miss_does_not_match() {
        assert!(!build_jail_net_allowed(None));
        assert!(!build_jail_net_allowed(Some(
            "definitely-not-in-the-catalog"
        )));
        assert!(!build_jail_net_allowed(Some("")));
        for listed in PACKAGE_NETWORK_ALLOWED {
            for impostor in [format!("{listed}-evil"), format!("evil-{listed}")] {
                assert!(
                    !build_jail_net_allowed(Some(&impostor)),
                    "`{impostor}` must not inherit `{listed}`'s entry"
                );
            }
            assert!(build_jail_net_allowed(Some(listed)));
        }
    }

    /// `binary_search` is only correct on a sorted slice, and the generator's sort is what makes
    /// it so. A future edit that emits insertion order instead would make the lookup silently
    /// MISS admitted packages — a fail-closed direction, but a wrong one, and quiet.
    #[test]
    fn the_generated_allow_set_is_sorted_and_deduplicated() {
        assert!(
            PACKAGE_NETWORK_ALLOWED.windows(2).all(|w| w[0] < w[1]),
            "PACKAGE_NETWORK_ALLOWED must be strictly ascending: {PACKAGE_NETWORK_ALLOWED:?}"
        );
    }
}
