//! Per-package egress: which dependency may reach the network under the build jail, and how
//! much of it.
//!
//! # The defense is PACKAGE IDENTITY, not host granularity
//!
//! This is the load-bearing premise and it is easy to get backwards. The attack the build
//! jail exists to blunt is the one Shai-Hulud used: an attacker publishes a new `postinstall`
//! into a package that never had one, and it runs with the user's full access. The package
//! is not one anybody vetted for network use — it is `chalk`, or whatever the worm reached.
//!
//! So the control that matters is the ENTRY, not the hostname. A package with no entry in
//! this table gets no egress, whatever hosts it asks for, and a package that needs egress
//! has to arrive through a pull request against `data/build-jail-catalog.json` first. That
//! PR is the whole opt-in mechanism.
//!
//! It follows that host granularity buys much less than it appears to. Narrowing an admitted
//! host to a URL prefix would constrain a package somebody already reviewed and trusted; it
//! does nothing about the unvetted package, which is the actual threat. The `pathShape` the
//! catalog records is therefore PROVENANCE — what the package was observed to fetch — and not
//! a gate. Do not build enforcement around it.
//!
//! # Why `Full` exists and is not a compromise
//!
//! Some packages cannot be described by a host list at all: `node-libcurl` git-clones vcpkg
//! and then reaches vcpkg's own per-port download hosts, a set nothing enumerates;
//! `windows-build-tools` picks its mirror from a runtime network probe; `hasura-cli`'s
//! postinstall is not even present in its published tarball. For those, unrestricted egress
//! for THAT package is the honest grant, and it is sanctioned rather than tolerated: the
//! package is one we looked at and admitted, and the alternative is a broken install plus a
//! catalog that lies about what it covers.
//!
//! # NOT YET ENFORCED — the jail's egress is still GLOBAL
//!
//! Read this before relying on anything above. `preset::build_jail_net` compiles to
//! `["$downloads"]` for EVERY jailed lifecycle spawn, and `compile_build_jail`'s
//! `package_name` reaches only the filesystem axis. So today a package with no entry still
//! reaches all of `DOWNLOAD_HOSTS`, and the package-identity gate this module describes is
//! data without an enforcer.
//!
//! Closing that is the single highest-value change the catalog now makes possible, and it is
//! deliberately not done here: flipping egress to per-package denies the network to every
//! package the corpus did not name, which is the intended design but a behavioral change that
//! needs its own measurement pass. Tracked in the catalog as
//! `knownDefects: per-package-egress-not-enforced`.

/// What the catalog says one package may reach.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PackageNetwork {
    /// No entry. Under the model above this is "no egress" — see the module's enforcement
    /// caveat for why it is not that yet.
    NoEntry,
    /// The hosts this package was observed to fetch.
    Hosts(&'static [&'static str]),
    /// Unrestricted egress, because a host list cannot describe this package.
    Full,
}

// THE TABLES ARE DATA, NOT CODE. Generated by `build.rs`: the host lists are INVERTED from
// `networkHosts[].fetchedBy` rather than authored package-first, so a host entry and its
// packages cannot drift apart. Only `packageNetwork.full` is authored here, because it is the
// one fact a host list cannot carry.
include!(concat!(env!("OUT_DIR"), "/package_network.rs"));

/// What `package_name` may reach. `None` — aube withheld the installer-resolved identity
/// because its root is a checkout it FETCHED — is [`PackageNetwork::NoEntry`], the
/// conservative direction and the same reading the curated filesystem table takes.
pub fn package_network(package_name: Option<&str>) -> PackageNetwork {
    let Some(name) = package_name else {
        return PackageNetwork::NoEntry;
    };
    if PACKAGE_NETWORK_FULL.contains(&name) {
        return PackageNetwork::Full;
    }
    PACKAGE_NETWORK_HOSTS
        .iter()
        .find(|(key, _)| *key == name)
        .map_or(PackageNetwork::NoEntry, |(_, hosts)| {
            PackageNetwork::Hosts(hosts)
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::DOWNLOAD_HOSTS;

    /// The authorship invariant, same as the curated filesystem table's: the key is the name
    /// the RESOLVER assigned, and the lookup is exact, so a package cannot rename itself into
    /// an entry. `None` matches nothing.
    #[test]
    fn only_an_exact_installer_resolved_name_matches() {
        assert_eq!(package_network(None), PackageNetwork::NoEntry);
        for impostor in ["node-libcurl-x", "x-node-libcurl", "Node-LibCurl"] {
            assert_eq!(
                package_network(Some(impostor)),
                PackageNetwork::NoEntry,
                "{impostor} must not match a real entry"
            );
        }
    }

    /// `full` supersedes the inverted host list rather than sitting alongside it. Asserted
    /// against a package that legitimately appears under two hosts in `fetchedBy`, so a
    /// generator that merged instead of superseding would fail here.
    #[test]
    fn a_full_grant_supersedes_the_inverted_host_list() {
        assert_eq!(package_network(Some("node-libcurl")), PackageNetwork::Full);
        assert!(
            !PACKAGE_NETWORK_HOSTS
                .iter()
                .any(|(k, _)| *k == "node-libcurl"),
            "a full-network package must not also carry a host list — the two would disagree"
        );
    }

    /// Every host the inversion produced is one the egress allowlist actually admits. A
    /// package-first entry naming a host that is refused would be a grant nothing can honour.
    #[test]
    fn every_inverted_host_is_admitted() {
        for (pkg, hosts) in PACKAGE_NETWORK_HOSTS {
            assert!(!hosts.is_empty(), "{pkg} has an empty host list");
            for host in *hosts {
                assert!(
                    DOWNLOAD_HOSTS.contains(host),
                    "{pkg} names `{host}`, which is not in $downloads"
                );
            }
        }
    }

    /// The table has to actually cover the ecosystem it claims to, or the model above is
    /// describing an empty set. The corpus found 146 network-needing packages; the inversion
    /// plus the full grants must account for essentially all of them.
    #[test]
    fn the_table_covers_the_corpus_network_cohort() {
        let total = PACKAGE_NETWORK_HOSTS.len() + PACKAGE_NETWORK_FULL.len();
        assert!(
            total >= 140,
            "only {total} packages carry a network entry; the corpus measured 146 that need \
             one, so the table has lost coverage"
        );
    }
}
