//! The system library and header paths a native build needs to read.
//!
//! # Why this exists as a named axis
//!
//! 17 of 230 source-read lifecycle packages cannot build without reading a SYSTEM prefix —
//! `/usr/lib`, `/usr/include`, a Homebrew keg, the Xcode SDK's framework path — and 12 of
//! them need it on their DEFAULT build path, not a fallback. The catalog had no field for
//! that class, so the jail was not deliberately withholding those paths; it had never
//! represented them. Naming the axis is what turns a silent absence into a decision.
//!
//! # Why the grant is COARSE, and why that is the correct shape
//!
//! A per-package enumeration cannot work here, and the reason is mechanical rather than a
//! matter of taste: the paths are DISCOVERED AT BUILD TIME by executing `pkg-config`,
//! `pg_config`, `krb5-config` or `curl-config` during `binding.gyp` variable evaluation, and
//! their stdout is what supplies the include and link flags. Nothing in a manifest names
//! them. The 17 packages also do not cluster on one mechanism — they are the ordinary native
//! long tail (OpenSSL, ODBC, X11, Postgres, Kerberos, libsecret, JDK, Xcode frameworks) — so
//! any enumeration is already wrong for the eighteenth package.
//!
//! What makes coarse acceptable rather than merely convenient: these directories are
//! world-readable and hold no secrets, so READ on them confers nothing a dependency could
//! not get by vendoring its own copy of a header. The grant is read-only.
//!
//! # NOT YET ENFORCED
//!
//! Nothing folds these into [`super::preset::build_jail_surface`] yet. Wiring them changes
//! the granted read set on every platform and interacts with each backend's minimal-root
//! closure, which is a measured change rather than a data change — tracked in the catalog as
//! `knownDefects: system-paths-not-enforced`. Until then this module is the recorded
//! recommendation, generated from the same file as the evidence behind it so the two cannot
//! drift.

// THE PATHS ARE DATA, NOT CODE — generated by `build.rs` from the `systemPaths.platforms`
// object of `data/build-jail-catalog.json`, which carries a `why` per entry and the 17
// packages that need them. Same reasoning as `DOWNLOAD_HOSTS`: a malformed catalog is a build
// failure, and there is no runtime parse to get wrong.
include!(concat!(env!("OUT_DIR"), "/system_paths.rs"));

/// The host platform's system read paths.
///
/// Split by `cfg` rather than returning all three, because a policy is a statement about THIS
/// machine: granting Linux's multiarch dirs on macOS would be inert rules that a reader of the
/// compiled policy would have to explain away.
pub fn system_read_paths() -> &'static [&'static str] {
    #[cfg(target_os = "linux")]
    {
        SYSTEM_READ_PATHS_LINUX
    }
    #[cfg(target_os = "macos")]
    {
        SYSTEM_READ_PATHS_MACOS
    }
    #[cfg(windows)]
    {
        SYSTEM_READ_PATHS_WINDOWS
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos", windows)))]
    {
        &[]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The recommendation is worthless if the host platform resolves to nothing, and a `cfg`
    /// typo in the function above is exactly how that would happen silently on one platform
    /// while the other two stayed green.
    #[test]
    fn the_host_platform_resolves_to_a_non_empty_set() {
        assert!(
            !system_read_paths().is_empty(),
            "no system read paths for this target — the cfg arms in system_read_paths() and \
             the catalog's systemPaths.platforms keys have diverged"
        );
    }

    /// build.rs rejects a glob at build time, so no test can construct one; the reachable
    /// check is that the shipped catalog contains none. A `*` here could only widen a rule
    /// past the directory the entry names, since `subtree_globs` supplies the recursion.
    #[test]
    fn no_system_path_carries_a_glob() {
        for set in [
            SYSTEM_READ_PATHS_LINUX,
            SYSTEM_READ_PATHS_MACOS,
            SYSTEM_READ_PATHS_WINDOWS,
        ] {
            for path in set {
                assert!(
                    !path.contains('*') && !path.contains('?'),
                    "system read path `{path}` must name a directory, not a pattern"
                );
            }
        }
    }

    /// The read-only property is the whole reason a coarse grant is admissible, and the one
    /// thing a future edit could break without any other test noticing: a `~`-anchored or
    /// project-relative entry would leave the world-readable-system-prefix argument behind
    /// while still compiling.
    #[test]
    fn every_system_path_is_absolute_or_env_anchored() {
        for set in [
            SYSTEM_READ_PATHS_LINUX,
            SYSTEM_READ_PATHS_MACOS,
            SYSTEM_READ_PATHS_WINDOWS,
        ] {
            for path in set {
                let anchored = path.starts_with('$') || path.starts_with('%');
                let absolute =
                    path.starts_with('/') || path.as_bytes().get(1).is_some_and(|b| *b == b':');
                assert!(
                    anchored || absolute,
                    "system read path `{path}` is neither absolute nor `$VAR`/`%VAR%`-anchored"
                );
            }
        }
    }
}
