'use client';

import { useMemo, useRef, useState } from 'react';
import data from '@/data/package-extensions.json';

// The whole `@nubjs/extensions` database as a paginated, filterable table, ranked
// by weekly npm downloads. Generated by scripts/gen-extensions-table.mjs, which
// pins the database version so the row count keeps agreeing with the prose
// around it.
//
// The rows ship in the client bundle rather than behind an endpoint: the filter
// has to be instant, the whole dataset is ~70 KB of short-keyed JSON, and a
// blog post that needs a running API to render its own evidence is worse.

/** `[target, "<class><field>"]`, both single characters. See the JSON legend. */
type Edge = [target: string, code: string];
type Row = { n: string; d: number | null; t: Edge[]; y?: number };

const PAGE_SIZE = 25;

// Rank is the position in the FULL download ordering, so a filtered view still
// tells you where a package sits in the ecosystem rather than renumbering 1..n.
const ROWS = data.rows as unknown as Row[];
const RANK = new Map(ROWS.map((row, index) => [row.n, index + 1]));

// Every annotation after an import name — the class and the field alike — gets
// ONE treatment: the same size, weight and colour, with no chip, border or
// italic. Three treatments for the same kind of note read as three kinds of
// thing, which is what the earlier bordered `dependency` chip and italic field
// labels did. The WORD carries the meaning; the title says what the word means.
const LABEL = 'ml-1 text-[11px] text-fd-muted-foreground';

// The four classes the scan assigns, plus `-` for an edge carried from Yarn's
// database that the scan never saw. Every one of them is labelled: an unlabelled
// import reads as "no class" rather than as a class the reader has to infer. The
// titles say what the class IS; none of them rates how serious it is.
const CLASS_LABEL: Record<string, { text: string; title: string }> = {
  r: { text: 'runtime', title: 'Imported on the package’s main entry graph' },
  a: { text: 'adapter', title: 'A framework or backend peer the application supplies' },
  g: { text: 'guarded', title: 'Loaded inside a try/catch' },
  t: { text: 'types', title: 'Referenced from a declaration file' },
  '-': {
    text: 'unscanned',
    title: 'Carried from @yarnpkg/extensions; the scan never saw this import',
  },
};

// How the entry ships. An optional peer is the default and carries no label — it
// is what all but a couple of hundred of these edges are, so labelling it would
// label almost every line. The three exceptions each get a word.
const FIELD_LABEL: Record<string, { text: string; title: string }> = {
  d: { text: 'dependency', title: 'Ships in dependencies, so the install adds the package' },
  q: { text: 'required peer', title: 'Ships as a peer dependency that is not optional' },
  o: {
    text: 'optional',
    title: 'The package already declares this peer; the rule marks it optional',
  },
  p: { text: '', title: '' },
};

// Fixed locale: a client component still renders on the server, and letting
// Intl pick the runtime default makes the two disagree and trip hydration.
const NUMBER = new Intl.NumberFormat('en-US');

// How many rules came from Yarn's database. Counted from the data rather than
// written down, so it keeps agreeing with the rows after a database refresh.
const FROM_YARN = ROWS.filter((row) => row.y).length;

// Weekly downloads are context, not a figure anyone reads digit by digit, so the
// column shows a rounded magnitude and hands the exact count to the title. The
// thresholds keep every value at three or four characters: whole millions from
// 10M up, one decimal below that, whole thousands below 1M.
function compactDownloads(value: number) {
  const millions = value / 1_000_000;
  if (millions >= 9.95) return `${Math.round(millions)}M`;
  // Both remaining rounds are compared against the value they would PRINT, so a
  // count just under a threshold cannot render as `1000K` or `10.0M`.
  if (value >= 999_500) return `${millions.toFixed(1)}M`;
  if (value >= 1000) return `${Math.round(value / 1000)}K`;
  return String(value);
}

function Edges({ edges }: { edges: Edge[] }) {
  return (
    // The important modifier is load-bearing, not a shortcut: the blog's prose
    // typography styles bare `ul`/`li` from an unlayered sheet, which outranks
    // any Tailwind utility whatever its specificity. Left alone it put 17.5px of
    // margin above and below every cell's list and drove a one-line row to 89px.
    <ul className="!m-0 flex list-none flex-wrap gap-x-5 gap-y-1 !p-0">
      {edges.map(([target, code]) => {
        const cls = CLASS_LABEL[code[0]] ?? CLASS_LABEL['-'];
        const field = FIELD_LABEL[code[1]] ?? FIELD_LABEL.p;
        return (
          // Inline content, NOT a nested flex row. As a flex line the label was
          // baseline-aligned to the target's FIRST line, so a target long enough
          // to wrap left its label stranded at the far right of the cell. Inline
          // spans wrap as one run and the label stays against the name.
          // `min-w-0` defeats the flexbox automatic minimum size. Without it a
          // flex item refuses to shrink below its content's min-content width,
          // so on a phone 25 of 25 rows pushed their labels past the cell's
          // right edge instead of wrapping inside it.
          <li key={target} className="!m-0 min-w-0 !p-0">
            <span className="break-words font-mono text-[13px] text-fd-foreground">{target}</span>
            {/* A real space: adjacent JSX spans have no break opportunity between
                them, so on a phone the NAME broke mid-word ("@babel/typ es") before
                the label would wrap. With the space the label wraps first. */}{' '}
            {cls.text ? (
              <span className={LABEL} title={cls.title}>
                {cls.text}
              </span>
            ) : null}
            {/* And a second one, for the same reason: with the two labels welded
                into one run, `unscanned dependency` was 8px wider than a phone's
                imports column and ran under the cell's right edge. */}{' '}
            {field.text ? (
              <span className={LABEL} title={field.title}>
                {field.text}
              </span>
            ) : null}
          </li>
        );
      })}
    </ul>
  );
}

export function ExtensionsTable() {
  const [filter, setFilter] = useState('');
  const [page, setPage] = useState(1);
  const pane = useRef<HTMLDivElement>(null);

  // The pane holds its scroll offset across a page change, so a reader who
  // pages from halfway down row 13 would land halfway down the next page.
  function goTo(next: number) {
    setPage(next);
    pane.current?.scrollTo({ top: 0 });
  }

  const query = filter.trim().toLowerCase();
  const matches = useMemo(
    () => (query ? ROWS.filter((row) => row.n.toLowerCase().includes(query)) : ROWS),
    [query],
  );
  const pages = Math.max(1, Math.ceil(matches.length / PAGE_SIZE));
  // Clamped rather than reset: a filter change already sends `page` back to 1,
  // and clamping keeps the render honest if anything else ever shrinks the list.
  const current = Math.min(page, pages);
  const shown = matches.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE);

  const button =
    'rounded-md border border-fd-border px-2.5 py-1 text-fd-muted-foreground transition-colors hover:text-fd-foreground disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:text-fd-muted-foreground';

  return (
    <figure className="my-6">
      <div className="mb-3 flex flex-wrap items-center gap-3 text-sm">
        <label className="sr-only" htmlFor="extensions-filter">
          Filter by package name
        </label>
        <input
          id="extensions-filter"
          type="search"
          value={filter}
          placeholder="Filter by package name"
          onChange={(event) => {
            setFilter(event.target.value);
            goTo(1);
          }}
          className="min-w-0 flex-1 rounded-md border border-fd-border bg-transparent px-2.5 py-1 text-sm placeholder:text-fd-muted-foreground focus:outline-none focus:ring-1 focus:ring-fd-ring"
        />
        <span className="whitespace-nowrap text-fd-muted-foreground">
          {NUMBER.format(matches.length)} {matches.length === 1 ? 'package' : 'packages'}
        </span>
      </div>

      {/* `relative` on the scroll container, as on the tool matrix: the sr-only
          label text is absolutely positioned, and an absolute box is clipped
          only by a POSITIONED overflow ancestor. The frame sits on the
          container so it stays put while a phone scrolls the columns.

          The height is FIXED, and that is what keeps Previous/Next under the
          cursor: a page's rows are as tall as the imports they carry, and the
          32 pages measured anywhere from 793px to 2101px at desktop width. Left
          to flow, every click moved the controls by up to 1300px. A minimum
          height cannot fix that — only a fixed one can — so the rows scroll
          inside the pane and everything around them stays put. The `min()`
          keeps the pane inside a short window; it tracks the viewport, which
          does not change while paging. */}
      <div
        ref={pane}
        className="relative h-[min(65vh,30rem)] overflow-auto rounded-lg border border-fd-border sm:h-[min(75vh,44rem)] [&_table]:my-0"
      >
        {/* No minimum width on a phone, deliberately. A 30rem floor here is what
            the tool matrix uses, but this table's substantive column is the LAST
            one: at 390px the floor pushed all but ~30px of the imports off the
            right edge, so a reader saw three metadata columns and a sliver of
            the evidence. Below `sm` the table fits the viewport instead and the
            names wrap; taller rows beat a hidden column. The floor returns at
            `sm`, where the columns are wide enough to earn it. */}
        <table className="extensions-table w-full table-fixed rounded-none border-0 text-left text-sm sm:min-w-[30rem]">
          <colgroup>
            {/* The downloads column is sized by its HEADING now, not by its
                widest value: a compact count is four characters, so `downloads`
                on the second header line is the long word the column has to
                hold — 4.5rem at the phone's `text-xs`, 6rem at `text-sm` above
                it. Every rem freed here goes to the imports column. */}
            <col className="w-8 sm:w-11" />
            <col className="w-[34%] sm:w-[32%]" />
            <col className="w-[4.5rem] sm:w-24" />
            <col />
          </colgroup>
          <thead>
            <tr className="border-b border-fd-border bg-fd-muted/40">
              <th
                scope="col"
                className="px-2 py-2.5 text-right font-medium text-fd-muted-foreground sm:px-3"
              >
                #
              </th>
              <th scope="col" className="px-2 py-2.5 font-medium text-fd-muted-foreground sm:px-3">
                Package
              </th>
              <th
                scope="col"
                className="px-2 py-2.5 text-right text-xs font-medium text-fd-muted-foreground sm:px-3 sm:text-sm"
              >
                Weekly downloads
              </th>
              <th scope="col" className="px-2 py-2.5 font-medium text-fd-muted-foreground sm:px-3">
                Undeclared imports
              </th>
            </tr>
          </thead>
          <tbody>
            {shown.map((row) => (
              <tr key={row.n} className="border-b border-fd-border/60 last:border-0">
                <td className="px-2 py-2.5 text-right align-top tabular-nums text-fd-muted-foreground sm:px-3">
                  {RANK.get(row.n)}
                </td>
                <td className="px-2 py-2.5 align-top sm:px-3">
                  <a
                    href={`https://www.npmjs.com/package/${row.n}`}
                    className="break-words font-mono text-[13px]"
                  >
                    {row.n}
                  </a>
                </td>
                <td className="px-2 py-2.5 text-right align-top text-xs tabular-nums text-fd-muted-foreground sm:px-3 sm:text-sm">
                  {row.d === null ? (
                    <span title="npm returned no download count for this package">&mdash;</span>
                  ) : (
                    <span title={`${NUMBER.format(row.d)} weekly downloads`}>
                      {compactDownloads(row.d)}
                    </span>
                  )}
                </td>
                <td className="px-2 py-2.5 align-top sm:px-3">
                  <Edges edges={row.t} />
                </td>
              </tr>
            ))}
            {shown.length === 0 ? (
              <tr>
                <td colSpan={4} className="px-3 py-6 text-center text-fd-muted-foreground">
                  No package matches that filter.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      <div className="mt-3 flex items-center justify-between gap-3 text-sm">
        <button
          type="button"
          className={button}
          aria-label="Previous page"
          disabled={current <= 1}
          onClick={() => goTo(current - 1)}
        >
          Previous
        </button>
        {/* Fixed width and tabular figures: the readout is the one thing in this
            row whose text changes on every click, and a proportional `1` → `11`
            re-centres the whole line under the reader's cursor. */}
        <span
          aria-live="polite"
          className="min-w-[7rem] text-center tabular-nums text-fd-muted-foreground"
        >
          Page {NUMBER.format(current)} of {NUMBER.format(pages)}
        </span>
        <button
          type="button"
          className={button}
          aria-label="Next page"
          disabled={current >= pages}
          onClick={() => goTo(current + 1)}
        >
          Next
        </button>
      </div>

      <figcaption className="mt-2.5 text-center text-xs leading-relaxed text-fd-muted-foreground">
        Package data from {data._source} {data.version}. Weekly downloads for {data.downloads.start}{' '}
        to {data.downloads.end}. {NUMBER.format(FROM_YARN)} of the {NUMBER.format(ROWS.length)}{' '}
        entries are carried from @yarnpkg/extensions.
      </figcaption>
    </figure>
  );
}
