'use client';

import { Popover, PopoverContent, PopoverTrigger } from 'fumadocs-ui/components/ui/popover';
import { type ReactNode, useMemo, useRef, useState } from 'react';
import data from '@/data/package-extensions.json';

// The whole `@nubjs/extensions` database as a paginated, filterable table, ranked
// by weekly npm downloads. Generated by scripts/gen-extensions-table.mjs, which
// pins the database version so the row count keeps agreeing with the prose
// around it.
//
// The rows ship in the client bundle rather than behind an endpoint: the filter
// has to be instant, the whole dataset is ~70 KB of short-keyed JSON, and a
// blog post that needs a running API to render its own evidence is worse.

/** `[target, "<class><field>"]`, both single characters. See the JSON legend. */
type Edge = [target: string, code: string];
type Row = { n: string; d: number | null; t: Edge[]; y?: number };

const PAGE_SIZE = 25;

// Rank is the position in the FULL download ordering, so a filtered view still
// tells you where a package sits in the ecosystem rather than renumbering 1..n.
const ROWS = data.rows as unknown as Row[];
const RANK = new Map(ROWS.map((row, index) => [row.n, index + 1]));

// An import shows its NAME and nothing else. The class the scan assigned and the
// field the rule ships in are both in the data, but as visible labels they made
// the column a run of unexplained words (`unscanned dependency`, `guarded`,
// `optional`) beside every name, and the reader's question — which imports does
// this package fail to declare? — is answered by the names alone. Both survive
// in the name's tooltip, as sentences that name the two packages: how the
// import goes undeclared, then what the rule does about it.
function describe(pkg: string, target: string, code: string) {
  const P = <Name>{pkg}</Name>;
  const T = <Name>{target}</Name>;
  // A carried rule whose peer the package ALREADY declares is not a phantom at
  // all — Yarn only relaxes it to optional — so it gets its own sentence rather
  // than the class sentence, which would claim an undeclared import that is
  // declared.
  if (code[1] === 'o') {
    return (
      <>
        {P} already declares {T} as a peer dependency. The rule, carried from{' '}
        <Name>@yarnpkg/extensions</Name>, only marks that peer optional so an install without it
        succeeds.
      </>
    );
  }
  const how: Record<string, ReactNode> = {
    r: (
      <>
        {P} imports {T} from its main entry graph without declaring it. The import is not guarded,
        so under a strict layout it fails as soon as that code runs.
      </>
    ),
    a: (
      <>
        {P} imports {T} but never declares it as a peer. The application normally supplies it, but a
        strict linker cannot connect the two until the peer is declared.
      </>
    ),
    g: (
      <>
        {P} imports {T} inside a try/catch without declaring it. When the package is missing the
        import throws and the optional feature turns off.
      </>
    ),
    t: (
      <>
        The declaration files of {P} import {T} without declaring it. Nothing fails at runtime, but{' '}
        <Name>tsc</Name> reports TS2307 inside those files, or with <Name>skipLibCheck</Name> the
        import silently becomes <Name>any</Name>.
      </>
    ),
    '-': (
      <>
        {P} imports {T} without declaring it, according to <Name>@yarnpkg/extensions</Name>. This
        rule is carried from there, and Nub’s scan did not classify the import.
      </>
    ),
  };
  const ships: Record<string, ReactNode> = {
    d: (
      <>
        The rule adds {T} to <Name>dependencies</Name>, so installing {P} installs it.
      </>
    ),
    q: <>The rule adds {T} as a required peer dependency.</>,
    p: <>The rule adds {T} as an optional peer dependency, which installs nothing on its own.</>,
  };
  return (
    <>
      {how[code[0]] ?? how['-']} {ships[code[1]] ?? ships.p}
    </>
  );
}

// The prose's inline-code pill, restated: the popover is portalled outside the
// blog's prose scope, so a bare `code` here would pick up none of it.
function Name({ children }: { children: string }) {
  return (
    <code className="rounded-[5px] border border-fd-border/60 bg-fd-muted px-1 py-0.5 font-mono text-[12px] text-fd-foreground">
      {children}
    </code>
  );
}

// Fixed locale: a client component still renders on the server, and letting
// Intl pick the runtime default makes the two disagree and trip hydration.
const NUMBER = new Intl.NumberFormat('en-US');

// How many rules came from Yarn's database. Counted from the data rather than
// written down, so it keeps agreeing with the rows after a database refresh.
const FROM_YARN = ROWS.filter((row) => row.y).length;

// Weekly downloads are context, not a figure anyone reads digit by digit, so the
// column shows a rounded magnitude and hands the exact count to the title. The
// thresholds keep every value at three or four characters: whole millions from
// 10M up, one decimal below that, whole thousands below 1M.
function compactDownloads(value: number) {
  const millions = value / 1_000_000;
  if (millions >= 9.95) return `${Math.round(millions)}M`;
  // Both remaining rounds are compared against the value they would PRINT, so a
  // count just under a threshold cannot render as `1000K` or `10.0M`.
  if (value >= 999_500) return `${millions.toFixed(1)}M`;
  if (value >= 1000) return `${Math.round(value / 1000)}K`;
  return String(value);
}

// The explanation opens on hover and on focus, and on a tap where there is no
// hover. A popover rather than a `title`: the native tooltip takes a second to
// appear, renders two sentences in the OS's smallest type, and never shows on a
// touch screen. The popover is portalled, so the scroll pane's overflow cannot
// clip it, and Radix flips it to whichever side has room.
function Phantom({ pkg, target, code }: { pkg: string; target: string; code: string }) {
  const [open, setOpen] = useState(false);
  // Radix toggles on click, which on a mouse would CLOSE a popover that hover
  // just opened. A click that arrives while hovered is cancelled before Radix
  // sees it; a tap has no hover, so it still opens.
  const hovered = useRef(false);
  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger
        type="button"
        // The prose's inline-code pill, so a name reads as the same kind of thing
        // as the package names in the paragraphs above. The open state darkens
        // it, which is the one visual tie between a name and its popover.
        className="cursor-help whitespace-normal break-words rounded-[5px] border border-fd-border/60 bg-fd-muted px-1.5 py-0.5 text-left font-mono text-[13px] text-fd-foreground transition-colors data-[state=open]:bg-fd-accent"
        onPointerEnter={(event) => {
          if (event.pointerType !== 'mouse') return;
          hovered.current = true;
          setOpen(true);
        }}
        onPointerLeave={() => {
          hovered.current = false;
          setOpen(false);
        }}
        onClick={(event) => {
          if (hovered.current) event.preventDefault();
        }}
      >
        {target}
      </PopoverTrigger>
      <PopoverContent
        side="top"
        align="start"
        className="max-w-[22rem] p-3 text-[13px] leading-relaxed"
        // Neither auto-focus: focus moving INTO the content would fire the
        // trigger's pointer-leave and close it, and focus returning to the
        // trigger on close paints a focus ring on every name the pointer has
        // passed over.
        onOpenAutoFocus={(event) => event.preventDefault()}
        onCloseAutoFocus={(event) => event.preventDefault()}
      >
        {describe(pkg, target, code)}
      </PopoverContent>
    </Popover>
  );
}

function Edges({ pkg, edges }: { pkg: string; edges: Edge[] }) {
  return (
    // The important modifier is load-bearing, not a shortcut: the blog's prose
    // typography styles bare `ul`/`li` from an unlayered sheet, which outranks
    // any Tailwind utility whatever its specificity. Left alone it put 17.5px of
    // margin above and below every cell's list and drove a one-line row to 89px.
    <ul className="!m-0 flex list-none flex-wrap gap-x-1.5 gap-y-1.5 !p-0">
      {edges.map(([target, code]) => (
        // `min-w-0` defeats the flexbox automatic minimum size. Without it a
        // flex item refuses to shrink below its content's min-content width, so
        // on a phone a long scoped name ran past the cell's right edge instead
        // of wrapping inside it.
        <li key={target} className="!m-0 min-w-0 !p-0">
          <Phantom pkg={pkg} target={target} code={code} />
        </li>
      ))}
    </ul>
  );
}

export function ExtensionsTable() {
  const [filter, setFilter] = useState('');
  const [page, setPage] = useState(1);
  const pane = useRef<HTMLDivElement>(null);

  // The pane holds its scroll offset across a page change, so a reader who
  // pages from halfway down row 13 would land halfway down the next page.
  function goTo(next: number) {
    setPage(next);
    pane.current?.scrollTo({ top: 0 });
  }

  const query = filter.trim().toLowerCase();
  const matches = useMemo(
    () => (query ? ROWS.filter((row) => row.n.toLowerCase().includes(query)) : ROWS),
    [query],
  );
  const pages = Math.max(1, Math.ceil(matches.length / PAGE_SIZE));
  // Clamped rather than reset: a filter change already sends `page` back to 1,
  // and clamping keeps the render honest if anything else ever shrinks the list.
  const current = Math.min(page, pages);
  const shown = matches.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE);

  const button =
    'rounded-md border border-fd-border px-2.5 py-1 text-fd-muted-foreground transition-colors hover:text-fd-foreground disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:text-fd-muted-foreground';

  return (
    <figure className="my-6">
      <div className="mb-3 flex flex-wrap items-center gap-3 text-sm">
        <label className="sr-only" htmlFor="extensions-filter">
          Filter by package name
        </label>
        <input
          id="extensions-filter"
          type="search"
          value={filter}
          placeholder="Filter by package name"
          onChange={(event) => {
            setFilter(event.target.value);
            goTo(1);
          }}
          className="min-w-0 flex-1 rounded-md border border-fd-border bg-transparent px-2.5 py-1 text-sm placeholder:text-fd-muted-foreground focus:outline-none focus:ring-1 focus:ring-fd-ring"
        />
        <span className="whitespace-nowrap text-fd-muted-foreground">
          {NUMBER.format(matches.length)} {matches.length === 1 ? 'package' : 'packages'}
        </span>
      </div>

      {/* `relative` on the scroll container, as on the tool matrix: the sr-only
          label text is absolutely positioned, and an absolute box is clipped
          only by a POSITIONED overflow ancestor. The frame sits on the
          container so it stays put while a phone scrolls the columns.

          The height is FIXED, and that is what keeps Previous/Next under the
          cursor: a page's rows are as tall as the imports they carry, and the
          32 pages measured anywhere from 793px to 2101px at desktop width. Left
          to flow, every click moved the controls by up to 1300px. A minimum
          height cannot fix that — only a fixed one can — so the rows scroll
          inside the pane and everything around them stays put. The `min()`
          keeps the pane inside a short window; it tracks the viewport, which
          does not change while paging. */}
      <div
        ref={pane}
        className="relative h-[min(65vh,30rem)] overflow-auto rounded-lg border border-fd-border sm:h-[min(75vh,44rem)] [&_table]:my-0"
      >
        {/* No minimum width on a phone, deliberately. A 30rem floor here is what
            the tool matrix uses, but this table's substantive column is the LAST
            one: at 390px the floor pushed all but ~30px of the imports off the
            right edge, so a reader saw three metadata columns and a sliver of
            the evidence. Below `sm` the table fits the viewport instead and the
            names wrap; taller rows beat a hidden column. The floor returns at
            `sm`, where the columns are wide enough to earn it. */}
        <table className="extensions-table w-full table-fixed rounded-none border-0 text-left text-sm sm:min-w-[30rem]">
          <colgroup>
            {/* The downloads column is sized by its HEADING now, not by its
                widest value: a compact count is four characters, so `downloads`
                on the second header line is the long word the column has to
                hold — 4.5rem at the phone's `text-xs`, 6rem at `text-sm` above
                it. Every rem freed here goes to the imports column. */}
            <col className="w-8 sm:w-11" />
            <col className="w-[34%] sm:w-[32%]" />
            <col className="w-[4.5rem] sm:w-24" />
            <col />
          </colgroup>
          <thead>
            <tr className="border-b border-fd-border bg-fd-muted/40">
              <th
                scope="col"
                className="px-2 py-2.5 text-right font-medium text-fd-muted-foreground sm:px-3"
              >
                #
              </th>
              <th scope="col" className="px-2 py-2.5 font-medium text-fd-muted-foreground sm:px-3">
                Package
              </th>
              <th
                scope="col"
                className="px-2 py-2.5 text-right text-xs font-medium text-fd-muted-foreground sm:px-3 sm:text-sm"
              >
                Weekly downloads
              </th>
              <th scope="col" className="px-2 py-2.5 font-medium text-fd-muted-foreground sm:px-3">
                Phantom dependencies
              </th>
            </tr>
          </thead>
          <tbody>
            {shown.map((row) => (
              <tr key={row.n} className="border-b border-fd-border/60 last:border-0">
                <td className="px-2 py-2.5 text-right align-top tabular-nums text-fd-muted-foreground sm:px-3">
                  {RANK.get(row.n)}
                </td>
                <td className="px-2 py-2.5 align-top sm:px-3">
                  <a
                    href={`https://www.npmjs.com/package/${row.n}`}
                    className="break-words font-mono text-[13px]"
                  >
                    {row.n}
                  </a>
                </td>
                <td className="px-2 py-2.5 text-right align-top text-xs tabular-nums text-fd-muted-foreground sm:px-3 sm:text-sm">
                  {row.d === null ? (
                    <span title="npm returned no download count for this package">&mdash;</span>
                  ) : (
                    <span title={`${NUMBER.format(row.d)} weekly downloads`}>
                      {compactDownloads(row.d)}
                    </span>
                  )}
                </td>
                <td className="px-2 py-2.5 align-top sm:px-3">
                  <Edges pkg={row.n} edges={row.t} />
                </td>
              </tr>
            ))}
            {shown.length === 0 ? (
              <tr>
                <td colSpan={4} className="px-3 py-6 text-center text-fd-muted-foreground">
                  No package matches that filter.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      <div className="mt-3 flex items-center justify-between gap-3 text-sm">
        <button
          type="button"
          className={button}
          aria-label="Previous page"
          disabled={current <= 1}
          onClick={() => goTo(current - 1)}
        >
          Previous
        </button>
        {/* Fixed width and tabular figures: the readout is the one thing in this
            row whose text changes on every click, and a proportional `1` → `11`
            re-centres the whole line under the reader's cursor. */}
        <span
          aria-live="polite"
          className="min-w-[7rem] text-center tabular-nums text-fd-muted-foreground"
        >
          Page {NUMBER.format(current)} of {NUMBER.format(pages)}
        </span>
        <button
          type="button"
          className={button}
          aria-label="Next page"
          disabled={current >= pages}
          onClick={() => goTo(current + 1)}
        >
          Next
        </button>
      </div>

      <figcaption className="mt-2.5 text-center text-xs leading-relaxed text-fd-muted-foreground">
        Package data from {data._source} {data.version}. Weekly downloads for {data.downloads.start}{' '}
        to {data.downloads.end}. {NUMBER.format(FROM_YARN)} of the {NUMBER.format(ROWS.length)}{' '}
        entries are carried from @yarnpkg/extensions.
      </figcaption>
    </figure>
  );
}
