//! Static metadata for every setting in `settings.toml`.
//!
//! The `SETTINGS` slice is emitted at build time by `build.rs` from
//! the crate-local `settings.toml`. Each entry is a `'static`
//! borrow so there's zero runtime allocation and the compiler
//! verifies the schema shape at compile time.
//!
//! Read by `nub config` to describe, validate and route a setting.

/// Substitute the namespace tokens a `default` string may carry with nub's
/// directory names, so each name is spelled once, in [`NAMESPACE_TOKENS`],
/// rather than in every default that mentions it.
///
/// Identity for the defaults that carry no token — which is all of them but
/// the directory pair.
pub fn render_namespaces(raw: &'static str) -> std::borrow::Cow<'static, str> {
    if !NAMESPACE_TOKENS.iter().any(|(tok, _)| raw.contains(tok)) {
        return std::borrow::Cow::Borrowed(raw);
    }
    let mut out = raw.to_string();
    for (token, resolved) in NAMESPACE_TOKENS {
        out = out.replace(token, resolved);
    }
    std::borrow::Cow::Owned(out)
}

/// Every token [`render_namespaces`] understands, paired with the directory
/// name it resolves to. `cache_namespace` is deeper than `data_namespace` because the
/// engine's cache is one of several things nub keeps under `~/.cache/nub`,
/// while the store owns its namespace outright.
const NAMESPACE_TOKENS: &[(&str, &str)] =
    &[("{cache_namespace}", "nub/pm"), ("{data_namespace}", "nub")];

/// Metadata for one setting. Every field is `'static` because the
/// containing `SETTINGS` slice is a `const` built from string
/// literals at compile time.
#[derive(Debug, Clone, Copy)]
#[allow(dead_code)] // Fields are consumed by tests and future generators.
pub struct SettingMeta {
    /// pnpm-style canonical name (e.g. `preferFrozenLockfile`, `registries`)
    pub name: &'static str,
    /// TOML-ish type spec (e.g. `"bool"`, `"list<string>"`, `"\"highest\" | \"time-based\""`)
    pub type_: &'static str,
    /// Default value as a string (e.g. `"true"`, `"undefined"`).
    ///
    /// May carry a namespace TOKEN (`{cache_namespace}`, `{data_namespace}`)
    /// where the default names one of the tool's own directories. Display it
    /// through [`SettingMeta::rendered_default`], never raw — see that method
    /// for why the literal cannot live here.
    pub default: &'static str,
    /// CLI flags that set this setting
    pub cli_flags: &'static [&'static str],
    /// Environment variables that set this setting
    pub env_vars: &'static [&'static str],
    /// `.npmrc` keys that set this setting (aliases listed together;
    /// the first entry is treated as the canonical spelling)
    pub npmrc_keys: &'static [&'static str],
    /// `pnpm-workspace.yaml` keys that
    /// set this setting.
    pub workspace_yaml_keys: &'static [&'static str],
    /// Marks a setting as part of the npm-shared `.npmrc` surface:
    /// npm (and yarn / pnpm) read it from `.npmrc` too, so
    /// `nub config set` writes it there to keep the multi-tool
    /// contract. A setting only one tool reads leaves this `false`
    /// and routes to that tool's own config instead.
    pub npm_shared: bool,
    /// Marks a setting that shapes how `node_modules` is physically
    /// ARRANGED — the linker strategy, hoisting, the modules and
    /// virtual-store directories — as opposed to which version resolves
    /// or how a module is found. `config_read::branded_yaml` leaves these
    /// settings out.
    pub layout: bool,
}

impl SettingMeta {
    /// This setting's default, with any namespace token resolved to nub's
    /// directory names. Every surface that SHOWS a default to a user goes
    /// through here; reading [`SettingMeta::default`] raw prints the token.
    pub fn rendered_default(&self) -> std::borrow::Cow<'static, str> {
        render_namespaces(self.default)
    }
}

// Pulls in `pub const SETTINGS: &[SettingMeta] = &[...]` generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/settings_meta_data.rs"));

/// Every setting nub consumes, alphabetically sorted by name.
///
/// Filtered, not the raw table: a setting listed in
/// [`crate::UNSUPPORTED_SETTINGS`] is left out here, which takes it out of
/// every enumerating surface at once — `config list`, `config get`,
/// `config find`.
///
/// Reach for [`all_unfiltered`] only when a caller must see every entry of the
/// TABLE.
pub fn all() -> impl Iterator<Item = &'static SettingMeta> {
    SETTINGS.iter().filter(|meta| is_supported(meta.name))
}

/// The raw table, with nothing filtered out. See [`all`].
pub fn all_unfiltered() -> &'static [SettingMeta] {
    SETTINGS
}

/// Whether nub consumes `name`. False only for a setting listed in
/// [`crate::UNSUPPORTED_SETTINGS`].
pub fn is_supported(name: &str) -> bool {
    unsupported_advice(name).is_none()
}

/// The "use this instead" line for an unsupported setting, `None` when nub
/// consumes it.
pub fn unsupported_advice(name: &str) -> Option<&'static str> {
    crate::UNSUPPORTED_SETTINGS
        .iter()
        .find(|(declared, _)| *declared == name)
        .map(|(_, advice)| *advice)
}

/// The unsupported setting `key` spells, under its canonical name or any
/// declared `.npmrc` / workspace-YAML alias.
///
/// The inverse of what [`find`] will tell you: `find` reports an unsupported
/// setting as simply absent, which is right for every RESOLUTION path but wrong
/// for a user who typed the name — `config set` needs to say "not a setting
/// here" rather than write the key through as free-form config.
pub fn unsupported_for_key(key: &str) -> Option<&'static SettingMeta> {
    SETTINGS.iter().find(|meta| {
        !is_supported(meta.name)
            && (meta.name == key
                || meta.npmrc_keys.contains(&key)
                || meta.workspace_yaml_keys.contains(&key))
    })
}

/// Look up a setting by its canonical pnpm name. `SETTINGS` is
/// generated sorted by name (build.rs guarantees this via
/// `BTreeMap` iteration), so a binary search drops the lookup from
/// O(N) to O(log N). With ~120 entries and dozens of lookups per
/// command, the saving compounds across every startup.
///
/// The sort invariant is asserted in debug builds. A future hand
/// edit of `SETTINGS` (or a regression in the build.rs sort) would
/// silently flip valid lookups to `None`; the assert catches that
/// in test runs without slowing release builds.
///
/// A setting listed in [`crate::UNSUPPORTED_SETTINGS`] reports as ABSENT here.
/// Ask [`unsupported_for_key`] when the caller needs to distinguish "not a
/// setting" from "not a setting nub consumes".
pub fn find(name: &str) -> Option<&'static SettingMeta> {
    find_unfiltered(name).filter(|meta| is_supported(meta.name))
}

/// [`find`] without the unsupported filter — the TABLE's answer, for a caller
/// that must see every entry.
pub fn find_unfiltered(name: &str) -> Option<&'static SettingMeta> {
    debug_assert!(
        SETTINGS.windows(2).all(|w| w[0].name <= w[1].name),
        "SETTINGS must be sorted by name for find() to work"
    );
    SETTINGS
        .binary_search_by(|s| s.name.cmp(name))
        .ok()
        .map(|i| &SETTINGS[i])
}
